apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.app.name }}
  labels:
    name: {{ .Values.app.name }}
spec:
  containers:
  - name: {{ .Values.app.name }}
    image: {{ .Values.image.name }}
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 6000
